### PR TITLE
fixed new categories not showing in doc list dropdown

### PR DESCRIPTION
**Pull request by yneves**
Added `forceUpdate` property to `TableList` since it doesn't update unless the row changed.

### CODE REVIEW

**Comment by ntgn81** [comment]
@yneves , weird, if one of the docs change, shouldnt the list also be automatically changed?

**Comment by ntgn81** [comment]
I'd love to talk about it more. Merging for now!

**Comment by yneves** [comment]
@ntgn81 Yes, it does, but in this case no docs are changed, just the categories options for the dropdown.

**Comment by ntgn81** [comment]
Oh that makes sense!

**Pull request merged**
