### PR TITLE
Add help for deduplicate

### PR DESCRIPTION
**Pull request by yneves**

### CODE REVIEW

**Comment by yneves** [comment]
image

**Comment by JulieJager** [comment]
Just happen to jump in development and noticed when I click on any matter in the dashboard, this window pops-up.  You may still be working on this but I just wanted to let you know.  Otherwise, it looks good.

**Comment by yneves** [comment]
@JulieJager i just fixed it, Nam was faster to merge than i was to fix :-)

**Comment by JulieJager** [comment]
@yneves Great job!  I love the look and that it does NOT popup when you turn off NPL serial numbers.  :)

**Comment by ntgn81** [comment]
:tada:

**Pull request merged**
