### PR TITLE
move modal out of button

### PR DESCRIPTION
**Pull request by yneves**
This fixes the issue with file working only once.

### CODE REVIEW

**Comment by ntgn81** [comment]
Hmm, just missing the div broke it? Can you give me a short details, please?

**Comment by yneves** [comment]
I think the modal being inside the button was causing some event bubbling madness, it was also centering the content, which shouldn't happen.

**Comment by ntgn81** [comment]
Okay, can you please double check if we might have same issues with other modals?

**Comment by ntgn81** [comment]
If no issues with other modals, this is good to be merged 👍

**Comment by ntgn81** [comment]
@yneves

**Pull request merged**
