### PR TITLE
Feature/copy matter

### PR DESCRIPTION
**Pull request by yneves**
image

### CODE REVIEW

**Comment by yneves** [comment]
@ntgn81 I'm passing copied fields to create matter API, but getting Internal Server Error. Here's an example.

```
{
  "firmName": "toptalcom",
  "clientNumber": "Acme",
  "matterNumber": "340954308320948",
  "firstInventor": "First Name last",
  "priorityDate": "",
  "oneWayRelatedMatters": "",
  "twoWayRelatedMatters": "002,003,004,005,adsdasadasda2323123,007-1,0078,00781",
  "matterCategories": [
    "T5",
    "T4"
  ],
  "associateEmail": "nam.nguyena@toptal.com",
  "foreignAgentsEmail": "nam.nguyen@toptal.com", 
  "notes": "sdsasdsadsaasdads",
  "timing": "1",
  "statement": "2",
  "pairStatus": "",
  "examinerName": "asdsdaasdadsads"
}
```

**Comment by ntgn81** [comment]
The issue was with API not converting arrays into comma separated strings.

Do you always have details of the matter to be copied though? It might not be there if you're asking for it  the first time, right?

**Comment by yneves** [comment]
@ntgn81 It's fetching the matter from API.

**Comment by yneves** [comment]
@ntgn81 I changed the arrays to strings and still getting error 500.

**Comment by yneves** [comment]
@ntgn81 good to go?

**Comment by ntgn81** [comment]
Totally

**Comment by ntgn81** [comment]
Give me a bit, gotta push api changes out. I'll do that when I get home.

**Pull request merged**
