### PR TITLE
fix: dont restore value to original while saving doc changes

### PR DESCRIPTION
**Pull request by yneves**
It was annoying that when i finish editing any field of a document, it was restored to the previous value while the document was saved. I figured out that this happened because component state was being overwritten on `componentWillReceiveProps`. Let me know if i overlooked something, but i think we can remove this safely.

### CODE REVIEW

**Comment by ntgn81** [comment]
I did start noticing this recently too. Not sure what changed. `componentWillReceiveProps` shouldn't be called if nothing changed, which is the case here, until updated data comes back from server side.

We do want the state to be updated when new date comes back from server side, which can be triggered from outside of documents section.

Did you figure out what change triggered `componentWillReceiveProps` ?

**Comment by yneves** [comment]
@ntgn81 Makes sense. It's the notifications that's triggering it.

**Comment by ntgn81** [comment]
Hmm, how does notification trigger change on those components? They only have doc/categories as props, and those are not changed by notification, right?

**Comment by yneves** [comment]
@ntgn81 Seems the pure render function is always returning true in `DocumentsContainer`. I'm investigating.

**Comment by yneves** [comment]
We were doing the pure render thing wrong. Replaced `react-pure-render` with one that works with immutables.

**Comment by ntgn81** [comment]
Nice catch!

**Pull request merged**
