### PR TITLE
feature: npl dedup

### PR DESCRIPTION
**Pull request by yneves**
Implemented actions triggered by `DocumentActions`.
 * delete from matter, use same API as removing doc number
 * delete from client calls `delete-from-client` API which i think it's not available yet
 * dedup is calling `replace-doc-number`, it seems to be working, not sure if it needs tweaking for NPL
 * hold doesn't do anything yet

### CODE REVIEW

**Comment by ntgn81** [comment]
You're right, replace-doc-number is working for NPL. This is looking good! A few things though, see if you can look into it.

1. Let's just hide the NPL column until user switches to `dedup` mode, then we'll show the column with NPL# as editable text boxes. The NPL# the way it is, without being in dedup mode, is not too helpful for the users. Does this make sense?
1. Can we play with the column size to make the NPL# fit in? I think max is NPL### - 3 digits

**Comment by yneves** [comment]
Yeah, both makes sense. Since the column won't be visible all the time, it can be larger when it's visible.

**Comment by yneves** [comment]
@ntgn81 Pushed the changes.

**Comment by ntgn81** [comment]
Looks great, thanks!

**Pull request merged**
