### PR TITLE
reducing form spacing on matter and client

### PR DESCRIPTION
**Pull request by yneves**
Had to walk a long way to get these forms right without duplicating tons of code, as a bonus i tried to remove what was already duplicated.

### CODE REVIEW

**Comment by yneves** [comment]
image

**Comment by yneves** [comment]
image

**Comment by ntgn81** [comment]
@yneves , this is cool. Did you get rid of all references to Col/Row in our project? Might as well do that if we are just using div directly.

**Comment by yneves** [comment]
@ntgn81 Not all, but i think that's the way forward, Col/Row doesn't accept inline styles.

**Comment by ntgn81** [comment]
Okay, can you remove all references to Row/Col then? Shouldn't have too many of those, right?

**Comment by ntgn81** [comment]
Or it can be part of a separate PR, if so, feel free to merge this. It looks good 👍

**Comment by yneves** [comment]
Yeah, i'll do it in a new PR, should be just a few.

**Pull request merged**
