### PR TITLE
dedup modal

### PR DESCRIPTION
**Pull request by yneves**
Ready to review now.

### CODE REVIEW

**Comment by yneves** [comment]
image

**Comment by yneves** [comment]
Please don't merge until meeting, i'll show how it's working.

**Comment by yneves** [comment]
@ntgn81 This is ready to go but maybe we should integrate suggestion API first? Probably not useful without it.

**Comment by ntgn81** [comment]
@yneves , yep, let me work on API first

**Comment by yneves** [comment]
@ntgn81 need to get this api change merged https://github.com/syncids/syncids-api/pull/15 and then this is good to go

**Comment by ntgn81** [comment]
Done!

**Comment by yneves** [comment]
nice, thanks!

**Pull request merged**
