### PR TITLE
accept clientName together with clientNumber

### PR DESCRIPTION
**Pull request by yneves**

### CODE REVIEW

**Comment by ntgn81** [comment]
@yneves , looks like the is API already handling the clientName field, do you have any issues with the current API?

**Comment by ntgn81** [comment]
If not, feel free to merge it in

**Comment by yneves** [comment]
@ntgn81 The `clientList` field that's used for auto-complete doesn't contain `clientName` field. I can merge as its already prepared once you add it to the API.

**Comment by ntgn81** [comment]
Oh that one, yeah, I'll update it. Thanks

**Pull request merged**
