### PR TITLE
Release

### PR DESCRIPTION
**Pull request by ntgn81**

### CODE REVIEW

**Comment by JulieJager** [comment]
Looks great.  I can now access the matter she questioned where I could not before.  Thank you!

**Comment by ntgn81** [comment]
Wooo, nicely done, @yneves

**Comment by yneves** [comment]
:beers: @ntgn81

**Comment by JulieJager** [comment]
UGH.  I cannot seem to log in to Production using any web browser.  Log in button just spins a circle.  DEV works.

**Comment by JulieJager** [comment]
I can get in now.

**Comment by ntgn81** [comment]
Yep, the server got restarted it seems

**Comment by JulieJager** [comment]
Dang.  I cannot get in again.  Sorry for all the message.  Something is going on.

**Comment by ntgn81** [comment]
No problems! Can you try again? Just do what you were doing, I'll monitor the logs to see what crashed the server.

**Comment by JulieJager** [comment]
I have a conference call in a couple of mins so I cannot help yet.  I am back in now FYI

**Pull request merged**
