### PR TITLE
feature: auto suggest in npl documents

### PR DESCRIPTION
**Pull request by yneves**
Had to dig a little deeper for this one, but i think it's solid. I might try to send a PR to the react-autosuggest author and go back to using it if he accepts, it's just that he doesn't look very responsive about it.

### CODE REVIEW

**Comment by ntgn81** [comment]
Good try! I did try to do something similar. We might need to think over the behaviour a bit more though.

This implementation takes over up/down keys, which are valid actions on a text area to move up/down through lines when it's multple lines.

I did raise an issue on autosuggest, asking to let us ovewrite input-text with textarea. The author is quite responsive there.

https://github.com/moroshko/react-autosuggest/issues/127

**Comment by yneves** [comment]
I'll see what i can do. If the auto-complete is visible, it should take over the up/down keys, but if it's not (after hitting esc for example) it should release the keys. Since i'm already using the fork, i can change this there.

**Comment by ntgn81** [comment]
This does look better. I still don't like how non-standard it feels - there is no standard for autocompleted textarea anyway.

We can just go with this one for now, see how it's liked.

Two things though.

1. Can you make the suggest entries to be multiple lines? 3 Lines to match with the textarea row count
1. The change to that textarea does not seem to be triggering the update anymore for me. Is it just me?

**Comment by yneves** [comment]
Fixed both issues. Apparently the second one was already happening, not related to this change.

Hey @ntgn81 let's try to have this up for the meeting!

**Pull request merged**
