### PR TITLE
prevent spaces in matter id

### PR DESCRIPTION
**Pull request by yneves**
Prevent entering spaces and also remove them when triggering a change since you can still paste them in.

### CODE REVIEW

**Comment by ntgn81** [comment]
@juliejager, what do you want to do when user pastes the name with space in?

**Comment by JulieJager** [comment]
@ntgn81 Can we remove it for them?  Also, we should make sure spaces are removed from any cell in SyncIds.  Can we do that globally?

**Comment by ntgn81** [comment]
Sure. @yneves , can you remove spaces upon change please?

@JulieJager , do you mean to remove space from existing database? How should we handle duplicates after space removal then?

**Comment by JulieJager** [comment]
@ntgn81 I just mean if a user enters a space in the UI in the Client ID, Application No., Art Unit, etc., we remove the space for the client.

**Comment by ntgn81** [comment]
@JulieJager , no , I meant what if they already have matter `ABC` and `AB C` in database, did you wwant to somehow merge them?

**Comment by yneves** [comment]
@ntgn81 it's done already

**Comment by JulieJager** [comment]
@ntgn81 Ah.  Let me rethink this whole thing.  I'll be in touch soon.

**Pull request merged**
