### PR TITLE
Render on demand

### PR DESCRIPTION
**Pull request by yneves**
This is an experiment with rendering docs on demand. It's using `Waypoint` to detect when you scroll over the end of the list to trigger the rendering of another 100 docs. I'm hoping this makes possible to load huge matters. Can you merge so Julie can test and see if it feels better? Maybe try it yourself first? @ntgn81

### CODE REVIEW

**Comment by yneves** [comment]
@ntgn81 Did you have a chance to try this?

**Comment by ntgn81** [comment]
Sorry, I didnt. I'll take a look tomorrow.

**Comment by ntgn81** [comment]
Looks good to me! Can't quite see the difference on faster machines. But let's merge and see.

**Comment by JulieJager** [comment]
Currently, I have to wait 10 seconds or more to finish rendering US section for a large matter.  Hesitates a lot.  I am not able to use the side scroll bar when its "rendering."  I think this need a bit more work.  Can we return to dev for now?

**Comment by JulieJager** [comment]
In this example, it doesn't say rendering - just cut off in middle of foreign section.

capture

**Pull request merged**
