### PR TITLE
feature: clear input for duplicate documents

### PR DESCRIPTION
**Pull request by yneves**
The value of `clearNewDocument` switches from `false` to `true` to `false` when API response comes with `status: duplicate`. That causes the pure render check to be false, therefore allowing the component to change and clear the field.

That's not my favorite solution, i'm aware it seems hackish, but anything better than this would require a much broader change. I think we can live with it at least for now.

### CODE REVIEW

**Comment by ntgn81** [comment]
Totally agree here. Though having the duplicate check in generic `entities.js` isn't optimal.

Two other possible ways that I can think of.

1. Document components - clear `state.docNumber` after raising change if it's a new document. There'll be a flicker for as long as the ajax call goes on. Which might be acceptable.
2. Move the logic of setting the `clearNewDocument` flag inside modules/documents to keep it closer to the actual place, making `status === duplicate` looks more understandable.

**Comment by yneves** [comment]
Yeah, i'm trying to avoid the flicker and at the same time preserve the one-way flow. Moving it to `documents` sounds good, i'll do it.

**Comment by yneves** [comment]
@ntgn81 done

**Comment by ntgn81** [comment]
Thank you, sir. This looks good

**Pull request merged**
